CREATE TABLE IF NOT EXISTS meta_instance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  dialect VARCHAR(64) NOT NULL,
  engine VARCHAR(64),
  -- 存量部署需手动: ALTER TABLE meta_instance ADD COLUMN engine VARCHAR(64);
  host VARCHAR(255),
  port INT,
  database VARCHAR(255),
  db_user VARCHAR(255),
  password_ref VARCHAR(255),
  sslmode VARCHAR(32),
  connect_timeout_seconds INT,
  schemas TEXT,
  include_views BOOLEAN NOT NULL DEFAULT FALSE,
  metadata_version BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS meta_table (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instance_id BIGINT NOT NULL REFERENCES meta_instance(id) ON DELETE CASCADE,
  catalog VARCHAR(255) NOT NULL,
  schema_name VARCHAR(255) NOT NULL,
  table_name VARCHAR(255) NOT NULL,
  kind VARCHAR(32) NOT NULL DEFAULT 'table',
  position INT NOT NULL,
  UNIQUE (instance_id, catalog, schema_name, table_name)
);

CREATE TABLE IF NOT EXISTS meta_column (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_id BIGINT NOT NULL REFERENCES meta_table(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  type_declaration TEXT NOT NULL,
  position INT NOT NULL
);

CREATE TABLE IF NOT EXISTS meta_classification (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instance VARCHAR(255) NOT NULL,
  column_key VARCHAR(512) NOT NULL,
  category VARCHAR(32) NOT NULL,
  level VARCHAR(16) NOT NULL,
  source VARCHAR(16) NOT NULL,
  note VARCHAR(1024),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE (instance, column_key)
);

-- 存量库补列：spring.sql.init mode=always 每次启动执行；新库上无效果（幂等）
ALTER TABLE meta_table ADD COLUMN IF NOT EXISTS kind VARCHAR(32) NOT NULL DEFAULT 'table';

-- 查询网关选项（submitter / 放行姿态 / 方言能力覆盖）：存量库幂等补列
ALTER TABLE meta_instance ADD COLUMN IF NOT EXISTS submitter VARCHAR(16) NOT NULL DEFAULT 'jdbc';
ALTER TABLE meta_instance ADD COLUMN IF NOT EXISTS on_rewrite_failure VARCHAR(16) NOT NULL DEFAULT 'REJECT';
ALTER TABLE meta_instance ADD COLUMN IF NOT EXISTS top_n BOOLEAN;
ALTER TABLE meta_instance ADD COLUMN IF NOT EXISTS insert_overwrite BOOLEAN;
