server:
  port: 8080

spring:
  application:
    name: sql-mask

sqlmask:
  metadata-service:
    base-url: ${SQLMASK_METADATA_BASE_URL:}
    api-key: ${SQLMASK_METADATA_API_KEY:}
  policy-service:
    base-url: ${SQLMASK_POLICY_BASE_URL:}
    api-key: ${SQLMASK_POLICY_API_KEY:}
