server:
  port: 8082

spring:
  application:
    name: mask-metadata
  datasource:
    url: ${METADATA_PG_URL:jdbc:postgresql://127.0.0.1:5432/mask_metadata}
    username: ${METADATA_PG_USER:postgres}
    password: ${METADATA_PG_PASSWORD:postgres}
  sql:
    init:
      mode: always

metadata:
  api-key: ${METADATA_API_KEY:}
