-- mask-server: central authentication (simple mode) — one local user table
CREATE TABLE IF NOT EXISTS auth_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(128) NOT NULL UNIQUE,
  display_name VARCHAR(255),
  role VARCHAR(16) NOT NULL DEFAULT 'USER',
  groups_json TEXT,
  password_hash VARCHAR(512) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
