-- mask-server: central authentication (simple mode) — one local user table
CREATE TABLE IF NOT EXISTS auth_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(128) NOT NULL UNIQUE,
  display_name VARCHAR(255),
  role VARCHAR(16) NOT NULL DEFAULT 'USER',
  groups_json TEXT,
  password_hash VARCHAR(512) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- 审计事件（audit.store=jdbc 时使用）：关键过滤列 + 完整文档 JSON
CREATE TABLE IF NOT EXISTS audit_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(32) NOT NULL,
  outcome VARCHAR(16) NOT NULL,
  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
  actor_user VARCHAR(255),
  instance VARCHAR(255),
  resource_type VARCHAR(64),
  action VARCHAR(64),
  payload TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_event_time ON audit_event (occurred_at);
CREATE INDEX IF NOT EXISTS idx_audit_event_type ON audit_event (event_type, outcome);
